[versions]
# The latest versions are available at https://lambdaurora.dev/tools/import_quilt.html
minecraft = "1.19.1"
fabric_loader = "0.14.9"
fabric_api = "0.58.5+1.19.1"

cardinal_components_api = "5.0.1"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }

fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }

cardinal_components_api_base = { module = "dev.onyxstudios.cardinal-components-api:cardinal-components-base", version.ref = "cardinal_components_api" }
cardinal_components_api_entity = { module = "dev.onyxstudios.cardinal-components-api:cardinal-components-entity", version.ref = "cardinal_components_api" }

# If you have multiple similar dependencies, you can declare a dependency bundle and reference it on the build script with "libs.bundles.example".
[bundles]
fabric_api = ["fabric_api"]
cardinal_components_api = ["cardinal_components_api_base", "cardinal_components_api_entity"]

[plugins]
fabric_loom = { id = "fabric-loom", version = "1.0-SNAPSHOT" }
